{{- if .Values.jmx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-native.fullname" . }}-jmx-exporter
  labels:
    {{- include "kafka-native.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
data:
  jmx-exporter-config.yaml: |
    {{- toYaml .Values.jmx.config | nindent 4 }}
{{- end }}
