{{- if .Values.podDisruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kafka-native.fullname" . }}
  labels:
    {{- include "kafka-native.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  {{- with .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- else }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kafka-native.selectorLabels" . | nindent 6 }}
{{- end }}
