apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-native.fullname" . }}
  labels:
    {{- include "kafka-native.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.kafkaExporter.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.kafkaExporter.port }}"
    prometheus.io/path: /metrics
    {{- end }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: kafka
      targetPort: kafka
    {{- if .Values.kafkaExporter.enabled }}
    - port: {{ .Values.kafkaExporter.port }}
      protocol: TCP
      name: metrics
      targetPort: metrics
    {{- end }}
  selector:
    {{- include "kafka-native.selectorLabels" . | nindent 4 }}
