apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka-native.fullname" . }}
  labels:
    {{- include "kafka-native.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
