apiVersion: v2
name: tempo
description: Tempo distributed tracing
version: 1.0.0
dependencies:
  - name: tempo-distributed
    version: "3.0.6"
    repository: https://grafana-community.github.io/helm-charts
