environment: sandbox

tempo-distributed:
  ingester:
    replicas: 1
  distributor:
    replicas: 1
  querier:
    replicas: 1
  queryFrontend:
    replicas: 1
  compactor:
    replicas: 1

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
