environment: production

tempo-distributed:
  ingester:
    replicas: 3
  distributor:
    replicas: 2
  querier:
    replicas: 2
  queryFrontend:
    replicas: 2
  compactor:
    replicas: 1

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi
