apiVersion: v2
name: grafana
description: Grafana dashboards and datasources
version: 1.0.0
dependencies:
  - name: grafana
    version: "12.8.0"
    repository: https://grafana-community.github.io/helm-charts
