environment: sandbox

grafana:
  replicas: 1

  persistence:
    enabled: true

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 1500m
      memory: 256Mi

  grafana.ini:
    auth.anonymous:
      enabled: true
      org_role: Viewer
    auth.proxy:
      enabled: true
      header_name: X-Forwarded-User
      header_property: username
      auto_sign_up: true
      sync_ttl: 60
      whitelist: 127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
      headers: "Email:X-Forwarded-Email Groups:X-Forwarded-Groups"

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.authentication.svc.cluster.local:4180/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://auth.sandbox.example.com/oauth2/start?rd=$scheme://$host$request_uri"
      nginx.ingress.kubernetes.io/auth-response-headers: "X-Forwarded-User, X-Forwarded-Email, X-Forwarded-Groups"
      cert-manager.io/cluster-issuer: letsencrypt-staging
    hosts:
      - grafana-sandbox.your-domain.com
    path: /
    pathType: Prefix
    tls:
      - secretName: grafana-tls-sandbox
        hosts:
          - grafana-sandbox.your-domain.com
