environment: sandbox

grafana:
  replicas: 1

  persistence:
    enabled: true

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 1500m
      memory: 256Mi

  grafana.ini:
    auth.anonymous:
      enabled: true
      org_role: Viewer
