environment: sandbox

mimir-distributed:
  ingester:
    replicas: 1
    zoneAwareReplication:
      enabled: false

  distributor:
    replicas: 1

  querier:
    replicas: 1

  store_gateway:
    replicas: 1
    zoneAwareReplication:
      enabled: false

  compactor:
    replicas: 1

  # -- Reloadable runtime configuration (per-tenant overrides).
  #    Mimir reloads this every ~10s without restart.
  #    https://grafana.com/docs/mimir/latest/configure/about-runtime-configuration/
  runtimeConfig:
    overrides:
      INFRA:
        compactor_blocks_retention_period: 48h  # 30 days
        max_label_names_per_series: 60
      # Add more tenants as needed:
      # <tenant-id>:
      #   compactor_blocks_retention_period: 168h  # 7 days

  # Disable all extra caches to save cost/complexity unless query speed is slow
  chunks-cache: { enabled: false }
  index-cache: { enabled: false }
  metadata-cache: { enabled: false }
  results-cache: { enabled: false }

  global:
    extraEnv:
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP

  mimir:
    structuredConfig:
      memberlist:
        advertise_addr: ${MY_POD_IP}
      common:
        storage:
          backend: s3
          s3:
            insecure: true
            bucket_name: observability-k8s
            endpoint: obs-sandbox-minio.observability.svc.cluster.local:9000
            region: us-east-1
            access_key_id: admin
            secret_access_key: "eCEWI6JVf8uXZMuzs45LdooBfVp5p9Vj"
      blocks_storage:
        s3:
          bucket_name: observability-k8s
          endpoint: obs-sandbox-minio.observability.svc.cluster.local:9000
          region: us-east-1
        storage_prefix: tsdb

      alertmanager_storage:
        s3:
          bucket_name: observability-k8s
          endpoint: obs-sandbox-minio.observability.svc.cluster.local:9000
          region: us-east-1
        storage_prefix: alertmanager

      ruler_storage:
        s3:
          bucket_name: observability-k8s
          endpoint: obs-sandbox-minio.observability.svc.cluster.local:9000
          region: us-east-1
        storage_prefix: ruler

      # using setup from existing running mimir cluster
      ingest_storage:
        enabled: true
        kafka:
          address: kafka-native.observability.svc.cluster.local:9092
          topic: observability.metrics
          auto_create_topic_enabled: true
          auto_create_topic_default_partitions: 10
          producer_max_record_size_bytes: 15983616 # 20MB, adjust if you have larger samples or want to optimize for fewer/larger messages

      ruler:
        max_rules_per_rule_group: 50

